### ISSUE TITLE
DTLS support

### ISSUE THREAD

**Issue by Yamakaky** [sfackler/rust-security-framework#22]
The lib seems to support it https://developer.apple.com/reference/security/1654508-secure_transport

**Comment by sfackler** [comment]
I believe it already is? https://github.com/sfackler/rust-security-framework/blob/master/security-framework/src/secure_transport.rs#L117

**Comment by Yamakaky** [comment]
How, did see it, it's not in the doc https://sfackler.github.io/rust-security-framework/doc/v0.1.9/security_framework/secure_transport/enum.ConnectionType.html

**Comment by sfackler** [comment]
I must have forgotten to build the docs with the OSX_10_8 feature.
