### ISSUE TITLE
`Sync` and/or `Send` not implemented for various types

### ISSUE THREAD

**Issue by andrew-d** [sfackler/rust-security-framework#3]
I'm getting the following error in a project of mine:

```
src/main.rs:132:9: 132:22 note: `*mut security_framework_sys::base::OpaqueSecIdentityRef` cannot be shared between threads safely
src/main.rs:132:9: 132:22 note: required because it appears within the type `security_framework::identity::SecIdentity`
src/main.rs:132:9: 132:22 note: required because it appears within the type `Config`
```

I'm trying to fetch the identity from the keychain once, and then save it / pass it around to various threads that need it.  If `Security.framework` supports it, could you add the appropriate bounds?

**Comment by sfackler** [comment]
Yep, absolutely. I didn't batch-add those impls because I wasn't confident that they apply in all cases, but it should for `SecIdentity`.

**Comment by andrew-d** [comment]
Okay, doing some digging:

> On iOS, all the functions in this API are thread-safe and reentrant.
> In general, it is safe to use the functions in this API from threads other than your main thread, but you should avoid calling the function from multiple operations, work queues, or threads concurrently. 

So I think this means that most things can be `Send` but not `Sync` without any trouble?

**Comment by sfackler** [comment]
We have to be a bit careful here since these types are `Clone`able, so you can't rely on `&mut self` vs `&self`. Since `SecIdentity` is read-only, a `Send` bound should be fine.
