### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jchien14** [sfackler/rust-security-framework#37]
Hey, 
When you get a chance, think you could review PRs #34, #35, and then cut a release? I have some rust-native-tls work that depends on master and the outstanding PRs, and then some hyper-native-tls stuff on top of that so it'd be nice to clean up my local replaces a bit :)

Let me know if any of the open issues are blockers to a new release, and I'd be glad to help with them.

**Comment by mako-taco** [comment]
+1

**Comment by cjubb39** [comment]
A new build would be great!

**Comment by isg** [comment]
+10000

**Comment by sfackler** [comment]
Sorry for the delay, will cut one in a sec!

**Comment by sfackler** [comment]
Done!

**Comment by cjubb39** [comment]
Thanks so much!
